language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/infection

after_script:
  - php vendor/bin/coveralls -v
